# ~/.tmuxinator/dev.yml

project_name: dev
project_root: ~/
tabs:
  - main:
      layout: even-horizontal
      panes:
        - # empty, running bash
        - # empty, running bash
  - spill:
      layout: even-horizontal
      panes:
        - # empty, running bash
        - # empty, running bash
  - irssi:
      panes:
        - irssi
