# ~/.tmuxinator/dev.yml

project_name: dev
project_root: ~/
tabs:
  - main:
      layout: even-horizontal
      panes:
        - # empty, running bash
        - # empty, running bash
  - py3: 
      layout: even-horizontal
      panes:
        - vim
        - python3
  - R:
      layout: even-horizontal
      panes:
        - vim
        - R
  - irssi:
      panes:
        - irssi
